name: Deploy SaraSell Full Stack (Docker Compose) to GCP VM

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        
    # build frontend image
    - name: build frontend image
      run: |
        echo "docker build -t {secrets.DOCKER_USER}/studenthubapplication:frontend-latest ."
    - name: push docker frontend image 
      run: |
        echo "docker push {secrets.DOCKER_USER}/studenthubapplication:frontend-latest" 
        
    # 5️⃣ Deploy to GCP VM
    - name: Deploy to GCP VM using Docker Compose
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          echo "🔐 Logging into Docker Hub on VM"
          docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"

          echo "📥 Pulling latest images"
          docker pull stellarstacker/studenthubapplication:frontend-latest


          echo "🛑 Stopping old containers"
          docker compose down

          echo "🚀 Starting new containers"
          docker compose up -d

          echo "✅ Deployment finished"
