name: Deploy SaraSell Full Stack (Docker Compose) to GCP VM

on:
  push:
    branches: [ "erp/master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        
    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/studenthubapplication:frontend-latest .

    - name: Push frontend image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/studenthubapplication:frontend-latest

    - name: Deploy to GCP VM using Docker Compose
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"

          docker pull ${{ secrets.DOCKER_USER }}/studenthubapplication:frontend-latest

          docker compose down
          docker compose up -d
